### ISSUE TITLE
Use Exodus Privacy API to retrieve tracker signatures

### ISSUE THREAD

**Issue by U039b** [securisec/glorifiedgrep#1]
**Is your feature request related to a problem? Please describe.**
By now, tracker signatures are stored in a constant list in `constants.py`.

**Describe the solution you'd like**
I think it would be better to retrieve this list directly from the [Exodus Privacy API](https://github.com/Exodus-Privacy/exodus/wiki/REST_API). This way, the list used by glorifiedgrep would stay up-to-date.

**Describe alternatives you've considered**
NA

**Additional context**
API key is not required for the `/api/trackers` endpoint.

**Comment by securisec** [comment]
Actually, I did consider using the API at first, but didnt want a request to fire every time the lib is used. Maybe it would be a good design consideration to save the api output in a json file, with a param in the tracker method to update it on demand?

**Comment by securisec** [comment]
Due to the Exodus API having some odd patterns for certain trackers, i.e. `'CrowdTangle': '.'` which would match any character, the proposed solution is not directly implemented. What is being implemented is a new classmethod that can be used to override the built in trackers. This can be done by passing the text response to the classmethod. This feature will be released in  `0.9.4`

```python
from glorifiedgrep import GlorifiedAndroid
from glorifiedgrep.android.modules.constants import _Trackers
import requests

res = requests.get('https://reports.exodus-privacy.eu.org/api/trackers').text

_Trackers().exodus_trackers(res)
g = GlorifiedAndroid('/tmp/base.apk')
...
```

**Comment by U039b** [comment]
Code signatures provided by εxodus are valid regex. The `.` is there to match either `/` from dexdump output or `.` from Java source code. Each regex is peer-reviewed at least two times **before** publication.

**Comment by securisec** [comment]
I don't doubt that they are checked before publication, but simply speaking the `.` in the one I pointed out matches any character in regex. So that specific code signature for crowd tangle does not seem to be valid. Based on what you said about java source code, it would match every single character thus resulting in that tracker being detected even if it is not used.
